slam_toolbox:
  ros__parameters:
    use_sim_time: true
    
    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    mode: mapping  # localization, mapping, lifelong
    
    # SLAM Toolbox Parameters - OPTIMIZED FOR ACCURACY
    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.02  # Higher frequency for smoother mapping
    map_update_interval: 5.0
    resolution: 0.025               # Higher resolution (was 0.05) - like TurtleBot3
    max_laser_range: 12.0          # Reduced from 15.0 for better accuracy
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000
    enable_interactive_mode: true

    # General Parameters
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.2    # Reduced for more frequent updates
    minimum_travel_heading: 0.2     # Reduced for more frequent updates
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # Correlation Parameters - FINE-TUNED FOR ACCURACY
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01  # Higher resolution
    correlation_search_space_smear_deviation: 0.1

    # Loop Closure Parameters
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # Scan Matcher Parameters - OPTIMIZED
    distance_variance_penalty: 0.3      # Reduced for better matching
    angle_variance_penalty: 0.5         # Reduced for better matching
    fine_search_angle_offset: 0.00349   # ~0.2 degrees
    coarse_search_angle_offset: 0.349   # ~20 degrees
    coarse_angle_resolution: 0.0349     # ~2 degrees
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true