controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    # Controllers
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    lift_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:
    use_sim_time: true
    
    # Match the wheel joint names from URDF
    left_wheel_names: ["front_left_wheel_joint", "rear_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "rear_right_wheel_joint"]
    
    # Match dimensions from URDF properties
    wheel_separation: 0.7  # 2 * wheel_offset_y = 2 * 0.35
    wheel_radius: 0.1
    
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    
    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    
    open_loop: false
    position_feedback: true
    enable_odom_tf: true
    
    cmd_vel_timeout: 0.5
    
    # Velocity and acceleration limits
    linear:
      x:
        has_velocity_limits: true
        has_acceleration_limits: true
        max_velocity: 1.0
        max_acceleration: 1.0
        min_acceleration: -1.0
    
    angular:
      z:
        has_velocity_limits: true
        has_acceleration_limits: true
        max_velocity: 1.0
        max_acceleration: 1.0
        min_acceleration: -1.0

lift_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - lift_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    interpolation_method: spline

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true